import type { Store, Product } from './types';

export const STORES: Store[] = [
  { id: 1, name: 'Padaria Pão Quente', location: 'Centro, São Paulo', logoUrl: 'https://source.unsplash.com/100x100/?bakery' },
  { id: 2, name: 'Mercado Bom Preço', location: 'Vila Madalena, São Paulo', logoUrl: 'https://source.unsplash.com/100x100/?market' },
  { id: 3, name: 'Restaurante Sabor Caseiro', location: 'Pinheiros, São Paulo', logoUrl: 'https://source.unsplash.com/100x100/?restaurant' },
  { id: 4, name: 'Hortifruti Verde Vida', location: 'Jardins, São Paulo', logoUrl: 'https://source.unsplash.com/100x100/?fruits' },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Cesta de Pães Artesanais',
    description: 'Uma seleção de pães frescos do dia que não foram vendidos.',
    imageUrl: 'https://source.unsplash.com/400x300/?artisanal-bread-basket',
    originalPrice: 25.00,
    discountedPrice: 10.00,
    storeId: 1,
    expiryDate: 'Hoje',
    quantity: 5,
  },
  {
    id: 2,
    name: 'Kit de Frutas e Legumes',
    description: 'Frutas e legumes maduros, perfeitos para consumo imediato.',
    imageUrl: 'https://source.unsplash.com/400x300/?fresh-vegetables-fruits',
    originalPrice: 30.00,
    discountedPrice: 12.50,
    storeId: 4,
    expiryDate: 'Amanhã',
    quantity: 10,
  },
  {
    id: 3,
    name: 'Marmita do Chef',
    description: 'Prato do dia do nosso restaurante, delicioso e pronto para consumo.',
    imageUrl: 'https://source.unsplash.com/400x300/?gourmet-meal-box',
    originalPrice: 35.00,
    discountedPrice: 15.00,
    storeId: 3,
    expiryDate: 'Hoje',
    quantity: 8,
  },
  {
    id: 4,
    name: 'Caixa de Doces Variados',
    description: 'Doces e bolos do dia, uma surpresa deliciosa para sua sobremesa.',
    imageUrl: 'https://source.unsplash.com/400x300/?assorted-sweets-box',
    originalPrice: 40.00,
    discountedPrice: 18.00,
    storeId: 1,
    expiryDate: 'Hoje',
    quantity: 3,
  },
   {
    id: 5,
    name: 'Itens de Mercearia',
    description: 'Produtos com embalagem amassada ou perto da validade.',
    imageUrl: 'https://source.unsplash.com/400x300/?grocery-items',
    originalPrice: 50.00,
    discountedPrice: 20.00,
    storeId: 2,
    expiryDate: 'Próxima semana',
    quantity: 12,
  },
  {
    id: 6,
    name: 'Salada Fresca Montada',
    description: 'Saladas prontas que precisam ser consumidas rapidamente.',
    imageUrl: 'https://source.unsplash.com/400x300/?fresh-salad-bowl',
    originalPrice: 22.00,
    discountedPrice: 9.50,
    storeId: 3,
    expiryDate: 'Hoje',
    quantity: 6,
  },
  {
    id: 7,
    name: 'Iogurtes e Laticínios',
    description: 'Produtos lácteos com data de validade próxima.',
    imageUrl: 'https://source.unsplash.com/400x300/?dairy-products-yogurt',
    originalPrice: 18.00,
    discountedPrice: 7.00,
    storeId: 2,
    expiryDate: 'Amanhã',
    quantity: 15,
  },
  {
    id: 8,
    name: 'Sopa do Dia',
    description: 'Sopa nutritiva e quentinha, feita com ingredientes frescos.',
    imageUrl: 'https://source.unsplash.com/400x300/?hot-soup-bowl',
    originalPrice: 20.00,
    discountedPrice: 8.00,
    storeId: 3,
    expiryDate: 'Hoje',
    quantity: 9,
  }
];